### ISSUE TITLE
Text not rendered with certain font sizes

### ISSUE THREAD

**Issue by silverness2** [rougier/freetype-gl#210] opened 2019-07-16 20:28 UTC
I am using a version of freetype-gl from 2017 that I noticed is causing a seg fault with certain font sizes.

The offending font size appears to be `20.48`.

So, this week, I downloaded and compiled the latest freetype-gl to see if I could reproduce the issue with one of the existing freetype-gl demos, markup.c.

I took the markup.c source and only modified `line 109`:  I changed the `normal.size = 24.0` to `normal.size = 20.48`.  Then I recompiled and ran.  I do not get a seg fault, but any text with that size does not get rendered and I get the following error messages:
```
FT_Error (line 96, code 0x657465) : (null)
Unable to load "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf" (size=20.5)
Houston, we've got a problem !
```
Following is a screenshot of the markup.c demo when `normal.size` is set to `20.48`:

![ft](https://user-images.githubusercontent.com/25487118/61326932-12651d80-a7d5-11e9-96c7-e48c22001b0d.png)

It appears that the error message is originating from the `texture_font_load_face(...)` function in `texture_font.c`.  And though not 100% sure, the error might be associated with `FT_Set_Char_Size`.

Another strange thing is, if I set the `normal.size` value to any of the following values, the text gets rendered just fine:
```
20.4
20.47
20.478
20.5
20.6
24.48
```

Do you have any ideas of why this might be happening?  I am trying to figure out if there are sizes in general that might lead to this problem.

**Comment by rougier** [comment] 2019-07-24 08:42
You mean size 20.47 and 20.49 are fine but not 20.48 ? That would be weird.

**Comment by silverness2** [comment] 2019-07-24 18:21
Yes, that is correct.  `20.47` and `20.49` work properly, but `20.48` causes the above screenshot where any text with that size does not get rendered.

I'm testing this on Ubuntu 16.04.

**Comment by rougier** [comment] 2019-08-19 07:48
Sorry for late answer. That's really weird. Could you post a minimal script showing the problem (without rendering if possible).

**Comment by AlbertoGP** [comment] 2021-01-20 21:15
As I mentioned in #226, the actual FreeType error returned by `FT_Set_Char_Size()` is “**invalid ppem value**” because of the second parameter which is computed as `(int)(size * HRES)`.

For the font size `20.48` that value is `131072` and it fails, for `20.47` it is `131007` and it works.

The documentation for `FT_Set_Char_Size()` says the following:

> note
> While this function allows fractional points as input values, the resulting ppem value for the given resolution is always rounded to the nearest integer.
> https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_set_char_size

The type of that value is a 32 bit fixed-point number with the last 6 bits used for the fractional part, so rounding to the closest integer means rounding those bits up or down.

Looking in the source code for that function, we see that the rounding is not done there: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3335
The value is passed to `FT_Request_Size()` inside `req.width`: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3260 which then passes it to `error = clazz->request_size( face->size, req );` in https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3283

`clazz` is a `FT_Driver_Class` and I haven’t dug further there, so I’m not sure whether the promised size rounding gets done. Maybe it isn’t and that’s why we get the error.

I don’t know how those drivers work.

**Comment by rougier** [comment] 2021-01-21 09:46
Nice debug. But I still don't get why 20.47 and 20.49 are fine but not 20.48

**Comment by AlbertoGP** [comment] 2021-01-21 20:49
I’m looking now into the FT driver for truetype fonts: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/truetype/ttdriver.c

The driver’s `request_size` slot is assigned to the `tt_size_request()` function, which then calls `tt_size_reset()` and I think this is where the error message comes from. `tt_size_reset()` is in https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/truetype/ttobjs.c#L1302

There is only one place where that function returns `Invalid_PPem`:
```
    if ( size_metrics->x_ppem < 1 || size_metrics->y_ppem < 1 )
      return FT_THROW( Invalid_PPem );
```
That’s actually the *only* place in the whole FT code base that uses that error code!

`size_metrics` comes from the first parameter of `tt_size_reset(size, only_height)` as `FT_Size_Metrics*  size_metrics = &size->metrics;` and that `size` parameter comes from the first parameter of `tt_size_request(size, req)`, which is `face->size`.

Now the values of `face->size->metrics.x_ppem, .y_ppem` are **`65472, 2047`** for `20.47` and **`0, 2048`** for `20.48` **which is obviously what causes the error later on**.

Going back to `texture-font.c`, right after calling `FT_New_Face()` the `x_ppem, y_ppem` values are `0, 0` in both cases.
Those values get changed by the call to `FT_Set_Char_Size()` but not directly, only through `FT_Request_Size(face, req)`→`clazz->request_size(face->size, req)`/`tt_size_request(size, req)`→`tt_size_reset((TT_Size)size, 0)` where the error is detected and returned.

The only place in that call sequence that modifies those metrics is inside `tt_size_request()`, done by calling `FT_Request_Metrics(size->face, req)`: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3096

There `x_ppem, y_ppem` are calculated at `Calculate_Ppem:`: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3181

Lines that affect `x_ppem`:
```
      if ( req->type != FT_SIZE_REQUEST_TYPE_NOMINAL )
      {
        scaled_w = FT_MulFix( face->units_per_EM, metrics->x_scale );
      }
      metrics->x_ppem = (FT_UShort)( ( scaled_w + 32 ) >> 6 );
      ft_recompute_scaled_metrics( face, metrics );
```

`ft_recompute_scaled_metrics()` only adjusts the other metrics, does not touch `x_ppem`, and `metrics->x_ppem = (FT_UShort)( ( scaled_w + 32 ) >> 6 );` is just rounding of the 26.6-fixed-point value and conversion to integer, so the problem must come from `scaled_w = FT_MulFix( face->units_per_EM, metrics->x_scale );`, that is either `units_per_EM` or `x_scale` is `0`.

For both `20.48` and `20.47` font sizes, `units_per_EM` is `2048` and `x_scale` is `0` before calling `FT_Set_Char_Size()`.

Then we need to go again into `FT_Request_size()`→`clazz->request_size(face->size, req)`/`tt_size_request(size, req)`→`FT_Request_Metrics()` because it modifies `x_scale`: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3096

In `FT_Set_Char_Size()`, `req.type` is set to `FT_SIZE_REQUEST_TYPE_NOMINAL` and `req.width` to `(int)(size * HRES)` = `131072` for font size `20.48` which means that the relevant instructions that are executed are:
```
      FT_Long  w = 0, scaled_w = 0;
        w = h = face->units_per_EM;
      scaled_w = FT_REQUEST_WIDTH ( req );
        metrics->x_scale = FT_DivFix( scaled_w, w );
        scaled_w = FT_MulFix( face->units_per_EM, metrics->x_scale );
      metrics->x_ppem = (FT_UShort)( ( scaled_w + 32 ) >> 6 );
```

`FT_REQUEST_WIDTH` is defined in `include/freetype/internal/ftobjs.h` as:
```
#define FT_REQUEST_WIDTH( req )                                            \
          ( (req)->horiResolution                                          \
              ? ( (req)->width * (FT_Pos)(req)->horiResolution + 36 ) / 72 \
              : (req)->width )
```

`req.horiResolution` comes from the call to `FT_Set_Char_Size()` in `texture-font.c` as `DPI * HRES`, and is `4608` in both cases, therefore in the failing case `scaled_w = FT_REQUEST_WIDTH(req)` is `131072 × (4608 + 36) ÷ 72 = 8454144`, in the passing case `131007 × (4608 + 36) ÷ 72 = 8449951.5 →(long) 8449951`.

Then `metrics->x_scale` is either `FT_DivFix(8454144, 2048)` (fail) or `FT_DivFix(8449951, 2048)` (pass). The implementation of `FT_DivFix()` is at: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftcalc.c#L252

Tracking what `FT_DivFix()` does seems quite tedious so I’ve written a self-contained program copying its definition to apply it to these numbers:
```
#include <stdio.h>

/* From fttypes.h */
  typedef signed int  FT_Int;
  typedef signed long  FT_Long;
  typedef unsigned long  FT_ULong;

/* From include/freetype/config/integer-types.h */
typedef unsigned int FT_UInt64; // 64-bit machine.

/* From src/base/ftcalc.h */
/* transfer sign, leaving a positive number;                        */
/* we need an unsigned value to safely negate INT_MIN (or LONG_MIN) */
#define FT_MOVE_SIGN( x, x_unsigned, s ) \
    if ( x < 0 )                         \
    {                                    \
      x_unsigned = 0U - (x_unsigned);    \
      s          = -s;                   \
    }

/* From include/freetype/internal/ftcalc.h */
#define NEG_LONG( a )                                \
          (FT_Long)( (FT_ULong)0 - (FT_ULong)(a) )

FT_Long
FT_DivFix( FT_Long  a_,
           FT_Long  b_ )
{
  FT_Int     s = 1;
  FT_UInt64  a, b, q;
  FT_Long    q_;


  a = (FT_UInt64)a_;
  b = (FT_UInt64)b_;

  FT_MOVE_SIGN( a_, a, s );
  FT_MOVE_SIGN( b_, b, s );

  q = b > 0 ? ( ( a << 16 ) + ( b >> 1 ) ) / b
      : 0x7FFFFFFFUL;

  q_ = (FT_Long)q;

  return s < 0 ? NEG_LONG( q_ ) : q_;
}


void main()
{
  long w = 2048;// units_per_EM
  long scaled_w_f = 131072 * (4608 + 36) / 72;
  long scaled_w_p = 131007 * (4608 + 36) / 72;
  printf("fail: %d, passing: %d\n", scaled_w_f, scaled_w_p);
  printf("fail: FT_DivFix( %d, %d ) = %d\n",
         scaled_w_f, w, FT_DivFix(scaled_w_f, w));
  printf("pass: FT_DivFix( %d, %d ) = %d\n",
         scaled_w_p, w, FT_DivFix(scaled_w_p, w));
}
```

Running this program results in the following:
```
fail: scaled_w = 8454144, pass: scaled_w = 8449951
fail: FT_DivFix( 8454144, 2048 ) = 0
pass: FT_DivFix( 8449951, 2048 ) = 1962976
```

**There you have it, that’s where the `0` comes from.**

The documentation for `FT_DivFIx()` says:
> Compute (a*0x10000)/b with maximum accuracy. Its main use is to divide a given value by a 16.16 fixed-point factor.
> https://www.freetype.org/freetype2/docs/reference/ft2-computations.html#ft_divfix

This looks like an arithmetic overflow to me, because `2048` interpreted as a 16.16-fixed-point value is less than `1.0` so the result must be bigger than the first argument, but it is smaller.
The hexadecimal representation of `8454144` is `0x810000`, maybe that’s how the overflow would end up with all zeros from those lower bytes while `8449951` = `0x80ef9f` and bigger values from bigger font sizes would not.

**Comment by AlbertoGP** [comment] 2021-01-22 10:01
Yes, it’s arithmetic overflow when `FT_UInt64` is 32 bits wide as I did above in that test program.
The strange thing is that when using the `FT_UInt64` value from the freetype includes, it is 8 bytes (64 bit) long so we should never get 0 as result:
```
/*
 * The compiler flags are from: build/CMakeFiles/freetype-gl.dir/flags.h
 * gcc -I/usr/include/freetype2 -o SIZEOF SIZEOF.c
 */

#include <stdio.h>
#include <freetype/freetype.h>

void main()
{
  FT_UInt64 a = 1234;
  printf("Size of FT_UInt64: %d\n", sizeof(a));
}
```
This shows `Size of FT_UInt64: 8` as it should, and this modified program computes the values correctly:
```
/*
 * The compiler flags are from: build/CMakeFiles/freetype-gl.dir/flags.h
 * gcc -I/usr/include/freetype2 -o DIVFIX DIVFIX.c
 */
#include <stdio.h>
#include <freetype/freetype.h>

/* From src/base/ftcalc.h */
/* transfer sign, leaving a positive number;                        */
/* we need an unsigned value to safely negate INT_MIN (or LONG_MIN) */
#define FT_MOVE_SIGN( x, x_unsigned, s ) \
    if ( x < 0 )                         \
    {                                    \
      x_unsigned = 0U - (x_unsigned);    \
      s          = -s;                   \
    }

/* From include/freetype/internal/ftcalc.h */
#define NEG_LONG( a )                                \
          (FT_Long)( (FT_ULong)0 - (FT_ULong)(a) )

FT_Long
FT_DivFix( FT_Long  a_,
           FT_Long  b_ )
{
  FT_Int     s = 1;
  FT_UInt64  a, b, q;
  FT_Long    q_;


  a = (FT_UInt64)a_;
  b = (FT_UInt64)b_;

  FT_MOVE_SIGN( a_, a, s );
  FT_MOVE_SIGN( b_, b, s );

  q = b > 0 ? ( ( a << 16 ) + ( b >> 1 ) ) / b
      : 0x7FFFFFFFUL;

  q_ = (FT_Long)q;

  return s < 0 ? NEG_LONG( q_ ) : q_;
}


void main()
{
  long w = 2048;// units_per_EM
  long scaled_w_f = 131072 * (4608 + 36) / 72;
  long scaled_w_p = 131007 * (4608 + 36) / 72;
  printf("fail: scaled_w = %d, pass: scaled_w = %d\n", scaled_w_f, scaled_w_p);
  printf("fail: FT_DivFix( %d, %d ) = %d\n",
         scaled_w_f, w, FT_DivFix(scaled_w_f, w));
  printf("pass: FT_DivFix( %d, %d ) = %d\n",
         scaled_w_p, w, FT_DivFix(scaled_w_p, w));
}
```
Result:
```
fail: scaled_w = 8454144, pass: scaled_w = 8449951
fail: FT_DivFix( 8454144, 2048 ) = 270532608
pass: FT_DivFix( 8449951, 2048 ) = 270398432
```

The next step to check is `scaled_w = FT_MulFix( face->units_per_EM, metrics->x_scale );`.

**Comment by AlbertoGP** [comment] 2021-01-22 10:14
Looking again into `freetype/src/base/ftcalc.c`, `FT_DivFix()` has two alternative definitions, one of which uses 32 bit integers:
```
#ifdef FT_LONG64
...
  FT_EXPORT_DEF( FT_Long )
  FT_DivFix( FT_Long  a_,
             FT_Long  b_ )
  {
    FT_Int     s = 1;
    FT_UInt64  a, b, q;
    FT_Long    q_;
    ...
  }
...
#else /* !FT_LONG64 */
...
  FT_EXPORT_DEF( FT_Long )
  FT_DivFix( FT_Long  a_,
             FT_Long  b_ )
  {
    FT_Int     s = 1;
    FT_UInt32  a, b, q;
    FT_Long    q_;
    ...
  }
...
#endif
```
Which means that the `libfreetype2` installed in the system (from the package manager in my case) was compiled without 64 bit integers, although the includes from the same package do define `FT_UInt64` as a 64-bit integer.

**Comment by AlbertoGP** [comment] 2021-01-22 21:04
Well, it turns out that this is a known issue in FreeType that is being worked on:

> Under linux on x86_64, sizeof(long) is 8. So even under strict ANSI, FT_LONG64 should be defined and 64-bit arithmetic should not be disabled. It is not right that I have to beg for it with FT_CONFIG_OPTION_FORCE_INT64 these days. 
Also 'long long' has been standard since C99, long enough, no punt intended.
https://gitlab.freedesktop.org/freetype/freetype/-/issues/475

**Comment by apodtele** [comment] 2021-01-23 03:52
`metrics->x_ppem = (FT_UShort)( ( scaled_w + 32 ) >> 6 );`

This also truncates the number to 16-bit. Why do you have such different x_ppem and y_ppem? 

Do not get me wrong. I think you are on the right path. I just want to understand the circumstances.

**Comment by AlbertoGP** [comment] 2021-01-23 09:19
Are you asking about the following statement?
> Now the values of `face->size->metrics.x_ppem, .y_ppem` are **`65472, 2047`** for `20.47` and **`0, 2048`** for `20.48` **which is obviously what causes the error later on**.

I do not see why you mention the truncation, you seem to imply that it should make the values more similar. What do you mean?
Please note that those lines I quoted are, as noted above the code block, “*the relevant instructions*” wrt. `x_ppem` which is the one checked in the conditional that returns the error. There is also a corresponding `metrics->y_ppem = (FT_UShort)( ( scaled_h + 32 ) >> 6 );` for `y_ppem` which we do not need to consider when following how `x_ppem` is computed:
https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3190
 
As for the difference, look at the call to `FT_Set_Char_Size()`, the `horz_resolution` and `vert_resolution` parameters:
https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3335
https://github.com/rougier/freetype-gl/blob/master/texture-font.c#L85

**Comment by AlbertoGP** [comment] 2021-01-25 10:48
@rougier: one of the FreeType maintainers replied that, while the compilation failing to detect 64-bit support is a defect, *freetype-gl* would not work in 32-bit machines and that the input to the FT functions might be unnecessarily big.

One question was about the multiplication of `x_ppem` by `HRES` which you explain at #224. So that’s clear.

The other is the multiplication of the `float size` parameter by `100.f` at https://github.com/rougier/freetype-gl/blob/master/texture-font.c#L240
```
    if (!texture_font_load_face(self, self->size * 100.f, &library, &face))
        return -1;
```
I’ve tested replacing that factor by `1.0` in all places it’s used, including the three mentions 20 lines further below in the same function where the scaling is undone, and the demos look exactly the same here.

Why is this needed?

**Comment by apodtele** [comment] 2021-01-25 13:36
FreeType returns outlines in 26.6 format (1/64th pixel resolution), which should certainly be enough for subpixel ticks. 

I still do not quite understand how you managed to compile with sizeof(FT_UInt64)=4.

**Comment by AlbertoGP** [comment] 2021-01-25 13:41
> I still do not quite understand how you managed to compile with sizeof(FT_UInt64)=4.

See the FreeType issue mentioned above.

**Comment by AlbertoGP** [comment] 2021-01-25 13:53
All right, I’ll run some more tests and, if things still look fine with 1.0 scaling, submit a PR.

**Comment by AlbertoGP** [comment] 2021-02-01 12:38
Finally got to the bottom of this, and it is arithmetic overflow.
However, it has nothing to do with that FreeType issue I mentioned earlier: https://gitlab.freedesktop.org/freetype/freetype/-/issues/475#note_781678

The confusion comes from the fact that `x_ppem` gets the value `0` for exactly the same values as if the `DivFix()` computation in FT was being performed in 32 bits, but the actual cause when computing in 64-bit is the final casting to 16-bit values for `x_ppem` and `y_ppem`.

The overflow is caused by that `100.f` scaling of the font size in `texture_font_init()` we talked about a few days ago.

I’ve made a new version of the overflow testing program (below) where you can set the font scaling (`scale`) and horizontal stretching (`HRES`), and also simulate 32-bit computation on a 64-bit machine.
With it we can see that, in both 32 and 64 bit, the maximum font size to avoid overflow is `1023`, which with the original factor of `100.f` becomes `10.23`. There was always overflow for fonts greater than that, but it was detected only for multiples of `10.24` (actual font size `1024` or `0x0400`): `20.48`, `30.72`, `40.96`, etc.

I’m preparing a PR that removes that scaling factor, and also corrects the commingling of `HRES` with the use of the factor `64` when converting between integers and 26.6 fixed-point numbers. This way we can adjust `HRES` and, if we set it to `1` (no horizontal stretching) set `FT_LOAD_TARGET_LIGHT` which as apodtele noted avoids horizontal hinting: https://gitlab.freedesktop.org/freetype/freetype/-/issues/475#note_781686
The rendering is not exactly the same as with `HRES = 64` but it’s closer than the default.

Here is the overflow issue reproduction program:
```c
/* Author: Alberto González Palomo <https://sentido-labs.com>
 *
 * With USE_FREETYPE_LIBRARY_FUNCTIONS:
 *   gcc -I/usr/include/freetype2 -lfreetype -o COMPUTE COMPUTE.c
 * Without:
 *   gcc -I/usr/include/freetype2 -o COMPUTE COMPUTE.c
 */
#include <stdio.h>
#include <freetype/freetype.h>

/* FT_LONG64 is defined by FreeType if it detects 64-bit support:
 * https://gitlab.freedesktop.org/freetype/freetype/-/issues/475
 */

// #define FT_LONG64 /* Force 64 bits. */
// #undef  FT_LONG64 /* Force 32 bits. */

//#define USE_FREETYPE_LIBRARY_FUNCTIONS

/* Conditions for reproducing #210:
 * https://github.com/rougier/freetype-gl/issues/210
 * - SCALE = 100.f
 * Turns out that 32-bit/64-bit does not make a difference:
 * with 32-bit we reach the invalid value 0 earlier,
 * but it fails for the same inputs.
 */
#ifdef FT_LONG64
#define FT_UIntXX FT_UInt64
#else
#define FT_UIntXX FT_UInt32
#endif
#define SCALE 100.f

#define HRES  64
#define HRESf 64.f
#define DPI   72

/* From src/base/ftcalc.h */
/* transfer sign, leaving a positive number;                        */
/* we need an unsigned value to safely negate INT_MIN (or LONG_MIN) */
#define FT_MOVE_SIGN( x, x_unsigned, s ) \
    if ( x < 0 )                         \
    {                                    \
      x_unsigned = 0U - (x_unsigned);    \
      s          = -s;                   \
    }

/* From include/freetype/internal/ftcalc.h */
#define NEG_LONG( a )                                \
          (FT_Long)( (FT_ULong)0 - (FT_ULong)(a) )

#ifndef USE_FREETYPE_LIBRARY_FUNCTIONS
/* Compute (a*0x10000)/b with maximum accuracy.
 * Its main use is to divide a given value by a 16.16 fixed-point factor.
 * a The numerator.
 * b The denominator. Use a 16.16 factor here.
 */
FT_Long
FT_DivFix( FT_Long  a_,
           FT_Long  b_ )
{
  FT_Int     s = 1;
  FT_UIntXX  a, b, q;// The original FT_DivFix() has two variants, FT_UInt32/64.
  FT_Long    q_;


  a = (FT_UIntXX)a_;
  b = (FT_UIntXX)b_;

  FT_MOVE_SIGN( a_, a, s );
  FT_MOVE_SIGN( b_, b, s );

  q = b > 0 ? ( ( a << 16 ) + ( b >> 1 ) ) / b
      : 0x7FFFFFFFUL;

  q_ = (FT_Long)q;

  return s < 0 ? NEG_LONG( q_ ) : q_;
}

// This is the 64-bit version of FT_MulDiv:
// https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftcalc.c#L173
// The 32-bit version is here:
// https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftcalc.c#L415
// It does not make a difference in our case because
// we reach overflow first in the horizontal axis.
FT_Long
FT_MulDiv( FT_Long  a_,
           FT_Long  b_,
           FT_Long  c_ )
{
  FT_Int     s = 1;
  FT_UInt64  a, b, c, d;
  FT_Long    d_;


  a = (FT_UInt64)a_;
  b = (FT_UInt64)b_;
  c = (FT_UInt64)c_;

  FT_MOVE_SIGN( a_, a, s );
  FT_MOVE_SIGN( b_, b, s );
  FT_MOVE_SIGN( c_, c, s );

  d = c > 0 ? ( a * b + ( c >> 1 ) ) / c
      : 0x7FFFFFFFUL;

  d_ = (FT_Long)d;

  return s < 0 ? NEG_LONG( d_ ) : d_;
}
#endif


/* From include/freetype/internal/ftobjs.h */
#define FT_REQUEST_WIDTH( req )                                            \
          ( (req)->horiResolution                                          \
              ? ( (req)->width * (FT_Pos)(req)->horiResolution + 36 ) / 72 \
              : (req)->width )
#define FT_REQUEST_HEIGHT( req )                                            \
          ( (req)->vertResolution                                           \
              ? ( (req)->height * (FT_Pos)(req)->vertResolution + 36 ) / 72 \
              : (req)->height )


/* Reproduce the relevant computations done in FreeType. */
void compute(float size, const char* label)
{
  FT_Size_Request req = calloc(1, sizeof(FT_Size_RequestRec));

  // Set by FT_Set_Char_Size(FT_Face face, FT_F26Dot6 char_width, FT_F26Dot6 char_height, FT_UInt horz_resolution, FT_UInt vert_resolution):
  FT_F26Dot6 char_width = (FT_F26Dot6)(size * 64.0);
  FT_F26Dot6 char_height = 0;
  FT_UInt horz_resolution = DPI * HRES;
  FT_UInt vert_resolution = DPI;
  // Inside FT_Set_Char_Size(): */
  if ( !char_width )
    char_width = char_height;
  else if ( !char_height )
    char_height = char_width;

  req->width = char_width;
  req->height = char_height;
  req->horiResolution = horz_resolution;
  req->vertResolution = vert_resolution;

  FT_Bool overflow_predicted =
      ( ( FT_REQUEST_WIDTH ( req ) + 32 ) >> 6 ) > 0xFFFF;// == x_ppem.

  if (overflow_predicted) {
    printf("For size %.2f I predict: OVERFLOW\n", size);
  } else {
    printf("For size %.2f I predict: no overflow\n", size);
  }

  FT_UShort face_units_per_EM = 2048;// Comes from the font file.
  FT_Long  w = 0, h = 0;
  w = h = face_units_per_EM;
  long scaled_w = FT_REQUEST_WIDTH ( req );
  long scaled_h = FT_REQUEST_HEIGHT ( req );

  FT_Size_Metrics*  metrics = calloc(1, sizeof(FT_Size_Metrics));
  /* determine scales */
  if ( req->width )
  {
    metrics->x_scale = FT_DivFix( scaled_w, w );

    if ( req->height )
    {
      metrics->y_scale = FT_DivFix( scaled_h, h );

      if ( req->type == FT_SIZE_REQUEST_TYPE_CELL )
      {
        if ( metrics->y_scale > metrics->x_scale )
          metrics->y_scale = metrics->x_scale;
        else
          metrics->x_scale = metrics->y_scale;
      }
    }
    else
    {
      metrics->y_scale = metrics->x_scale;
      scaled_h = FT_MulDiv( scaled_w, h, w );
    }
  }
  else
  {
    // This branch does not run because freetype-gl calls FT_Set_Char_Size()
    // with a non-zero char_width parameter, and that is req->width here.
  }

  FT_Long div_result = FT_DivFix(scaled_w, w);
  printf("%s: FT_DivFix( scaled_w = 0x%X, w = 0x%X ) = 0x%X%s\n",
         label, scaled_w, w, div_result,
         div_result? "": " ← FAILS ALREADY HERE");

  // Calculate_Ppem:
  /* calculate the ppems */
  // req->type is set to FT_SIZE_REQUEST_TYPE_NOMINAL in FT_Set_Char_Size().

  printf("%s: scaled_w = 0x%X, scaled_h = 0x%X\n",
         label, scaled_w, scaled_h);

  metrics->x_ppem = (FT_UShort)( ( scaled_w + 32 ) >> 6 );
  metrics->y_ppem = (FT_UShort)( ( scaled_h + 32 ) >> 6 );

  FT_UIntXX full_x_ppem = ( scaled_w + 32 ) >> 6;
  FT_UIntXX overflow = full_x_ppem - ((FT_UIntXX)metrics->x_ppem);
  if (overflow) {
    printf("%s: OVERFLOW detected: 0x%X - 0x%X = 0x%X, a factor of %f×.\n",
           label, full_x_ppem, metrics->x_ppem, overflow,
           ((double)full_x_ppem) / ((double)0xFFFF));
  } else {
    printf("%s: No overflow. Margin is %f×.\n",
           label, 1.0 - (double)full_x_ppem / (double)0xFFFF);
  }

  printf("%s: x_ppem = 0x%X, y_ppem = 0x%X%s\n",
         label, metrics->x_ppem, metrics->y_ppem,
         0 == metrics->x_ppem || 0 == metrics->y_ppem?
         " → INVALID PPEM VALUE":"");

  free(metrics);
  free(req);
}

void main(int argc, char* argv[])
{
  printf("sizeof(FT_UIntXX) = %d\n", sizeof(FT_UIntXX));
  printf("   FT_SIZEOF_LONG = %d\n", FT_SIZEOF_LONG);
  printf("sizeof(FT_UShort) = %d\n", sizeof(FT_UShort));
  for (int i = 1; i < argc; ++i) {
    compute(atof(argv[i]) * SCALE, argv[i]);
  }
  if (argc <= 1) {
    printf("You can specify a list of font sizes as arguments.\n");
    compute(20.47 * SCALE, "20.47 pass");
    compute(20.48 * SCALE, "20.48 fail");
    compute(20.49 * SCALE, "20.49 pass");
  }
}
```

**Comment by apodtele** [comment] 2021-02-01 14:06
Thank you for working on this robust implementation. It is hard to be objective with rendering results. We all have some preferences. The LIGHT mode might make some very think stems slightly thicker (adding weight and contrast) without shifting them at all. The vertical hinting might be slightly different from NORMAL (native bytecode) hinting: even height might be different. Different does not mean bad.

**Comment by rougier** [comment] 2021-02-08 10:05
I merged you PR. Many thanks for  the detailed debug and nice PR.

**Closed** 2021-02-08 10:04 UTC
